esigate-core/src/main/java/org/esigate/impl/UrlRewriter.java, esigate-core/src/main/java/org/esigate/util/UriUtils.java, esigate-core/src/test/java/org/esigate/impl/UrlRewriterTest.java
Improved rewriting rules base url and anchors
=> Added some unit tests to UrlRewriter

esigate-cas/src/test/java/org/esigate/cas/CasAuthenticationHandlerTest.java, esigate-core/src/main/java/org/esigate/Driver.java, esigate-core/src/main/java/org/esigate/RequestExecutor.java, esigate-core/src/main/java/org/esigate/authentication/GenericAuthentificationHandler.java, esigate-core/src/main/java/org/esigate/cookie/DefaultCookieManager.java, esigate-core/src/main/java/org/esigate/esi/InlineElement.java, esigate-core/src/main/java/org/esigate/extension/parallelesi/InlineElement.java, esigate-core/src/main/java/org/esigate/http/HeaderManager.java, esigate-core/src/main/java/org/esigate/http/HttpClientRequestExecutor.java, esigate-core/src/main/java/org/esigate/http/ResourceUtils.java, esigate-core/src/main/java/org/esigate/impl/DriverRequest.java, esigate-core/src/main/java/org/esigate/impl/UrlRewriter.java, esigate-core/src/main/java/org/esigate/test/TestUtils.java, esigate-core/src/main/java/org/esigate/util/HttpRequestHelper.java, esigate-core/src/main/java/org/esigate/vars/VariablesResolver.java, esigate-core/src/test/java/org/esigate/MockRequestExecutor.java, esigate-core/src/test/java/org/esigate/http/HeaderManagerTest.java, esigate-core/src/test/java/org/esigate/http/HttpClientRequestExecutorTest.java, src/site/xdoc/reference.xml
http://www.esigate.org/mantisbt/view.php?id=285
=> 0000285: Refactor URL rewriting code

src/site/xdoc/quickstart.xml
http://www.esigate.org/mantisbt/view.php?id=294
=> 0000294: Fix quick start page

esigate-app-aggregated1/pom.xml, esigate-app-aggregated2/pom.xml, esigate-app-aggregator/pom.xml, esigate-app-cas/pom.xml, esigate-app-casified-aggregated1/pom.xml, esigate-app-casified-aggregated2/pom.xml, esigate-app-casified-aggregator/pom.xml, esigate-app-master/pom.xml, esigate-app-provider/pom.xml, esigate-cas/pom.xml, esigate-core/pom.xml, esigate-distribution/pom.xml, esigate-server/pom.xml, esigate-servlet/pom.xml, esigate-war/pom.xml, pom.xml
This reverts commit eb4d9d0189f3d561c5f7a60c4abafc0ded11a8c8.
=> Revert "[maven-release-plugin] prepare release esigate-5.0-beta-3"

esigate-core/src/main/java/org/esigate/impl/UrlRewriter.java, esigate-core/src/test/java/org/esigate/impl/UrlRewriterTest.java
https://github.com/esigate/esigate/issues/87
=> UrlRewriter incorrectly rewrites some Urls in scripts #87

esigate-core/src/main/java/org/esigate/http/HeaderManager.java, esigate-core/src/main/java/org/esigate/impl/UrlRewriter.java, esigate-core/src/test/java/org/esigate/impl/UrlRewriterTest.java
https://github.com/esigate/esigate/issues/86
=> Rewrite meta refresh tag location in html pages #86

esigate-core/src/main/java/org/esigate/http/HttpResponseUtils.java, esigate-core/src/main/java/org/esigate/impl/UrlRewriter.java, esigate-core/src/main/java/org/esigate/test/TestUtils.java, esigate-servlet/src/main/java/org/esigate/servlet/impl/ResponseSender.java
Enable streaming
Javadoc fixes
=> Enable streaming

.gitignore, .travis.yml, README.md
Let's try to make this thing work !
=> Working Travis CI integration

esigate-app-aggregator/src/main/webapp/local/post.jsp, esigate-app-aggregator/src/test/java/org/esigate/test/cases/AggregatorTest.java, esigate-core/src/main/java/org/esigate/http/IncomingRequest.java, esigate-servlet/src/main/java/org/esigate/servlet/impl/HttpServletRequestEntity.java, esigate-servlet/src/main/java/org/esigate/servlet/impl/RequestFactory.java
https://github.com/esigate/esigate/issues/97
Created class httpServletRequestEntity that lazily obtains the
InputStream only when asked to do so
=> POST requests do not work with local providers #97

esigate-app-aggregator/src/test/java/org/esigate/test/cases/AggregatorTest.java
https://github.com/esigate/esigate/issues/97
=> Fixed unit tests that were broken under Linux due to crlf

esigate-servlet/src/main/java/org/esigate/servlet/ServletExtension.java, esigate-servlet/src/test/java/org/esigate/servlet/ServletExtensionTest.java, src/site/xdoc/reference.xml
https://github.com/esigate/esigate/issues/98
=> Background revalidation not compatible with ServletExtension #98

README.md, esigate-app-aggregator/src/test/java/org/esigate/test/cases/ResponseHeadersTest.java, esigate-core/src/main/java/org/esigate/extension/ForwardOriginalUrl.java, esigate-core/src/test/java/org/esigate/DriverTest.java, esigate-core/src/test/java/org/esigate/cookie/DefaultCookieManagerTest.java, esigate-core/src/test/java/org/esigate/esi/CommentTest.java, esigate-core/src/test/java/org/esigate/esi/IncludeElementTest.java, esigate-core/src/test/java/org/esigate/extension/parallelesi/CommentTest.java, esigate-core/src/test/java/org/esigate/extension/parallelesi/IncludeElementTest.java, esigate-core/src/test/java/org/esigate/http/HttpClientRequestExecutorTest.java, esigate-core/src/test/java/org/esigate/vars/DriverEsiVariablesTest.java, esigate-servlet/src/test/java/org/esigate/servlet/impl/HttpServletSessionTest.java, pom.xml, src/site/site.xml
https://github.com/esigate/esigate/issues/10
=> Fix website (github migration) #10

esigate-core/src/main/java/org/esigate/DriverFactory.java, esigate-core/src/test/java/org/esigate/DriverFactoryTest.java
http://www.esigate.org/mantisbt/view.php?id=292
=> 0000292: Remove esigate-ext.properties feature

esigate-core/src/test/java/org/esigate/xml/XpathRendererTest.java
http://www.esigate.org/mantisbt/view.php?id=224
Unable to reproduce the issue. Just added a unit test.
=> 0000224: xpath attribute (esi:include) has issue with html5

esigate-core/src/test/java/org/esigate/DriverTest.java
FetchEvent#getHttpRequest().getOriginal().getRequestLine().getUri() #23
https://github.com/esigate/esigate/issues/23
=> FetchEvent#getHttpResponse().getStatusLine().getUri() is not the same as

esigate-core/src/test/java/org/esigate/impl/UrlRewriterTest.java
https://github.com/esigate/esigate/issues/110
=> mailto: links are incorectly rewritten #110

esigate-core/src/main/java/org/esigate/renderers/ResourceFixupRenderer.java, esigate-core/src/test/java/org/esigate/renderers/ResourceFixupRendererTest.java
=> Correction bug MailTo

pom.xml
between log4j-over-slf4j.jar and slf4j-log4j12.jar
https://github.com/esigate/esigate/issues/119
=> Random exceptions in builds on drone.io and travis-ci due to conflict

esigate-core/src/main/java/org/esigate/vars/Operations.java, esigate-core/src/main/java/org/esigate/vars/VariablesResolver.java, esigate-core/src/test/java/org/esigate/vars/DriverEsiVariablesTest.java, esigate-core/src/test/java/org/esigate/vars/DriverEsiWhenTest.java
Satisfies https://github.com/esigate/esigate/issues/117
=> Add $exists() method from Akamai specification

esigate-core/src/main/java/org/esigate/vars/Operations.java, src/site/xdoc/reference.xml
Add $exists ESI test method #117
=> Minor fixes and documentation update

esigate-app-master/pom.xml, esigate-app-master/src/main/resources/esigate.properties, esigate-app-master/src/main/resources/log4j.properties, esigate-core/src/main/java/org/esigate/extension/FragmentLogging.java, esigate-core/src/main/java/org/esigate/http/OutgoingRequestContext.java
http://www.esigate.org/mantisbt/view.php?id=225
Cookies are now in FragmentLogging et FetchLogging logs.
=> 0000225: Add cookie info in logs.

src/site/xdoc/reference.xml
exchanges
http://www.esigate.org/mantisbt/view.php?id=115
=> 0000115: Add a section in the documentation to explain how to debug http

esigate-server/src/main/java/org/esigate/server/EsigateServer.java, esigate-server/src/site/xdoc/index.xml
=> jessionid configuration in esigate-server

esigate-core/src/main/java/org/esigate/extension/parallelesi/IncludeElement.java, esigate-core/src/test/java/org/esigate/extension/parallelesi/EsiTest.java, esigate-servlet/src/main/java/org/esigate/servlet/impl/ResponseSender.java, pom.xml, src/site/xdoc/reference.xml
=> NPE in tomcat logs

esigate-cas/src/test/java/org/esigate/cas/CasAuthenticationHandlerTest.java, esigate-core/src/main/java/org/esigate/test/PropertiesBuilder.java, esigate-core/src/test/java/org/esigate/DriverTest.java, esigate-core/src/test/java/org/esigate/extension/parallelesi/EsiTest.java, esigate-core/src/test/java/org/esigate/extension/surrogate/SurrogateTest.java, esigate-core/src/test/java/org/esigate/http/HttpClientRequestExecutorTest.java
https://github.com/esigate/esigate/issues/184
Properties builder
=> Build / test issues with Java 9 #184

esigate-core/src/main/java/org/esigate/test/conn/MockConnectionManager.java, esigate-core/src/test/java/org/esigate/DriverTest.java
https://github.com/esigate/esigate/issues/191
=> Race condition in unit tests

esigate-server/src/test/java/org/esigate/server/AbstractEsigateServerTest.java
...to prevent random test errors
=> Improve test startup and shutdown

esigate-core/pom.xml, esigate-core/src/main/java/org/esigate/http/ProxyingHttpClientBuilder.java, esigate-core/src/test/java/org/esigate/DriverHttpTest.java, esigate-core/src/test/java/org/esigate/http/RetryExtension.java, pom.xml
https://github.com/esigate/esigate/issues/185
=> Fix HttpClient retry handler
